### ISSUE TITLE
Projections restful api

### ISSUE THREAD

**Issue by gregoryyoung** [EventStore/docs.geteventstore.com#110]
needs documentation

**Comment by brentonannan** [comment]
Hey @gregoryyoung,

Are there any docs at all for this as yet? Even a WIP PR or something I could use to get an idea for it? Or, if you could point me to the right place in the source of the HTTP API?

Cheers.

**Comment by pgermishuys** [comment]
@brentonannan unfortunately there isn't anything yet, you can however find the API here
https://github.com/EventStore/EventStore/blob/release-v3.4.0/src/EventStore.Projections.Core/Services/Http/ProjectionsController.cs#L54

**Comment by brentonannan** [comment]
Thanks Pieter, I'll have a go at discerning what I need from there.

**Comment by gregoryyoung** [comment]
The other thing to look at is padmin which is basically a wrapper over the
apis

On Tue, Oct 13, 2015 at 7:32 AM, Brenton Annan <notifications@github.com>
wrote:

> Thanks Pieter, I'll have a go at discerning what I need from there.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/docs.geteventstore.com/issues/110#issuecomment-147619005>
> .
>



-- 
Studying for the Turing test

**Comment by brentonannan** [comment]
Thanks. I had the most success looking at the requests sent from the angular app in the web interface; the only thing I couldn't find is whether there's a root API discovery URL?

**Comment by ChrisChinchilla** [comment]
I feel this is mostly covered now, with the rendered swagger spec and the overview doc, but will tighten up when I overhaul the spec.
