### ISSUE TITLE
ExpectedVersion.EmptyStream documents incorrectly.

### ISSUE THREAD

**Issue by jbradford** [EventStore/docs.geteventstore.com#113]
Ref: https://github.com/EventStore/EventStore/issues/428
Needs to be updated on: http://docs.geteventstore.com/dotnet-api/3.0.0/optimistic-concurrency-and-idempotence/ (and all other versions).

**Comment by gregoryyoung** [comment]
this specifies the expectation that target stream does not yet exist.

This seems correct. What do you think it should be updated to?

**Comment by gregoryyoung** [comment]
Sorry:

"this specifies the expectation that the target stream has been explicitly
created, but does not yet have any user events written in it."

This is what I thought it did.

I am testing now it on an nonexisting stream. I don't remember what the
specified behaviour was then but I thought it should fail in that case

On Sun, Mar 22, 2015 at 10:23 AM, Jon Bradford <notifications@github.com>
wrote:

> Ref: EventStore/EventStore#428
> <https://github.com/EventStore/EventStore/issues/428>
> Needs to be updated on:
> http://docs.geteventstore.com/dotnet-api/3.0.0/optimistic-concurrency-and-idempotence/
> (and all other versions).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/docs.geteventstore.com/issues/113>.
>



-- 
Studying for the Turing test

**Comment by jbradford** [comment]
I believe the issue is when we had Create Stream as a separate operation, this would have meant something different. (Is it possible to get an empty stream now that there is no explicit create stream operation).

**Comment by gregoryyoung** [comment]
Yes there is. Set metadata on it.

On Sun, Mar 22, 2015 at 10:53 PM, Jon Bradford <notifications@github.com>
wrote:

> I believe the issue is when we had Create Stream as a separate operation,
> this would have meant something different. (Is it possible to get an empty
> stream now that there is no explicit create stream operation).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/docs.geteventstore.com/issues/113#issuecomment-84703475>
> .
>



-- 
Studying for the Turing test

**Comment by srogovtsev** [comment]
BTW, I tried that (setting metadata on a non-existing stream). That leads to interesting result: in WebGUI, under "streams changed", appears *metadata* stream (e.g. $$stream_id), but not the stream itself (stream_id). After first event that shows up too.

Is the stream in fact created on metadata write?

**Comment by gregoryyoung** [comment]
The metadata stream is created.

In v1 there was an explicit "CreateStream" that you could do. This
ExptyStream is actually a throwback to that. It now is considered "created
but empty if metadata has been set on it"

On Sun, Mar 22, 2015 at 11:18 PM, Serg Rogovtsev <notifications@github.com>
wrote:

> BTW, I tried that (setting metadata on a non-existing stream). That leads
> to interesting result: in WebGUI, under "streams changed", appears
> *metadata* stream (e.g. $$stream_id), but not the stream itself
> (stream_id). After first event that shows up too.
>
> Is the stream in fact created on metadata write?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/docs.geteventstore.com/issues/113#issuecomment-84708093>
> .
>



-- 
Studying for the Turing test

**Comment by srogovtsev** [comment]
It seems to me that now one of the ExpectedVersions (EmptyStream, NoStream)
is redundant - I could see no practical need in differentiating between "no
stream at all" and "metadata set, but still no stream". Is there?

**Comment by gregoryyoung** [comment]
Yes there is.

Two clients writing at the same time both expecting it to be created but
empty.

Same for NoStream

Two clients expecting metadata to have never been set and empty

On Sun, Mar 22, 2015 at 11:25 PM, Serg Rogovtsev <notifications@github.com>
wrote:

> It seems to me that now one of the ExpectedVersions (EmptyStream, NoStream)
> is redundant - I could see no practical need in differentiating between "no
> stream at all" and "metadata set, but still no stream". Is there?
>
> On Mon, Mar 23, 2015 at 12:19 AM, Greg Young <notifications@github.com>
> wrote:
>
> > The metadata stream is created.
> >
> > In v1 there was an explicit "CreateStream" that you could do. This
> > ExptyStream is actually a throwback to that. It now is considered
> "created
> > but empty if metadata has been set on it"
> >
> > On Sun, Mar 22, 2015 at 11:18 PM, Serg Rogovtsev <
> notifications@github.com
> > >
> > wrote:
> >
> > > BTW, I tried that (setting metadata on a non-existing stream). That
> leads
> > > to interesting result: in WebGUI, under "streams changed", appears
> > > *metadata* stream (e.g. $$stream_id), but not the stream itself
> > > (stream_id). After first event that shows up too.
> > >
> > > Is the stream in fact created on metadata write?
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/EventStore/docs.geteventstore.com/issues/113#issuecomment-84708093
> > >
> > > .
> > >
> >
> >
> >
> > --
> > Studying for the Turing test
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/EventStore/docs.geteventstore.com/issues/113#issuecomment-84708213
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/docs.geteventstore.com/issues/113#issuecomment-84708533>
> .
>



-- 
Studying for the Turing test

**Comment by srogovtsev** [comment]
I thought that metadata stream had their own version numbers that are used
in concurrency checking on metadata write. Am I wrong?

**Comment by gregoryyoung** [comment]
They do but you are writing to the data stream :)

On Sun, Mar 22, 2015 at 11:35 PM, Serg Rogovtsev <notifications@github.com>
wrote:

> I thought that metadata stream had their own version numbers that are used
> in concurrency checking on metadata write. Am I wrong?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/docs.geteventstore.com/issues/113#issuecomment-84709067>
> .
>



-- 
Studying for the Turing test

**Comment by gregoryyoung** [comment]
As I mentioned this goes back to a historical use case in v1 there was a
CreateStream operation. We changed how that worked. This was to limit the
breaking change

On Sun, Mar 22, 2015 at 11:39 PM, Greg Young <gregoryyoung1@gmail.com>
wrote:

> They do but you are writing to the data stream :)
>
> On Sun, Mar 22, 2015 at 11:35 PM, Serg Rogovtsev <notifications@github.com
> > wrote:
>
>> I thought that metadata stream had their own version numbers that are used
>> in concurrency checking on metadata write. Am I wrong?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/EventStore/docs.geteventstore.com/issues/113#issuecomment-84709067>
>> .
>>
>
>
>
> --
> Studying for the Turing test
>



-- 
Studying for the Turing test

**Comment by srogovtsev** [comment]
I still can't imagine a scenario where event write should be dependent on
the fact that metadata was set on the stream. Do you have an example?

**Comment by gregoryyoung** [comment]
"my client should only be writing to streams created by some other process"

Its not a common use case but there are some use cases for it

On Sun, Mar 22, 2015 at 11:41 PM, Serg Rogovtsev <notifications@github.com>
wrote:

> I still can't imagine a scenario where event write should be dependent on
> the fact that metadata was set on the stream. Do you have an example?
>
>
> On Monday, March 23, 2015, Greg Young <notifications@github.com> wrote:
>
> > They do but you are writing to the data stream :)
> >
> > On Sun, Mar 22, 2015 at 11:35 PM, Serg Rogovtsev <
> notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > wrote:
> >
> > > I thought that metadata stream had their own version numbers that are
> > used
> > > in concurrency checking on metadata write. Am I wrong?
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/EventStore/docs.geteventstore.com/issues/113#issuecomment-84709067
> > >
> > > .
> > >
> >
> >
> >
> > --
> > Studying for the Turing test
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/EventStore/docs.geteventstore.com/issues/113#issuecomment-84709250
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/docs.geteventstore.com/issues/113#issuecomment-84709460>
> .
>



-- 
Studying for the Turing test
