### ISSUE TITLE
Anomaly detection?

### ISSUE THREAD

**Issue by KrishnaPG** [EventStore/docs.geteventstore.com#137]
Thank you for sharing this good work.

Trying to verify if this can be used for *alert when something interesting happens in a stream* scenario.

i.e., can some one "listen" to a stream for "data changes"?

For example, if last 3 values are greater than the mean of the of last 8 data points then raise an alert (emit event).

Or, instead of emitting an event, it could create a new data point in a child stream, so that who ever is "listening" on that child stream can see that data point and do whatever is necessary.

````
Base stream:  v1   v2   v3   v4   v5   v6   v7   v8 ....
child stream:    .     .     .      .      1     .      .   .....
````

I am looking for creating "user defined functions" as "alert triggering" mechanism on streams, so that user can define his own "monitoring" javascript function to know about interesting changes on his data.

Can this package achieve such things? Creating child streams and listening on child streams for data changes etc..?

Any pointers or example would be of great help.

**Comment by gregoryyoung** [comment]
You could do this using projections or in outside code. I am going to close this as it should be on eventstore not on the docs project.

Cheers,

Greg
