### ISSUE TITLE
SSL/HTTPS

### ISSUE THREAD

**Issue by gregoryyoung** [EventStore/docs.geteventstore.com#146]
There used to be docs on setting this up, they should be checked and brought over/redone

https://github.com/EventStore/EventStore/wiki/Setting-Up-SSL-In-Windows
https://github.com/EventStore/EventStore/wiki/Setting-Up-SSL-In-Linux

**Comment by memark** [comment]
Once I get it up and running, I might be able to help you out with this.

**Comment by span** [comment]
I am trying to set up TLS on Ubuntu 14.04 but I have not been successful in following the old docs. In the new docs, there are only instructions for Windows.

I could easily put together an article for Linux if I just got it working so if you have any idea or input on how to do this with 3.9.3 I would love some help. The configuration looks very different from the new Windows docs.

**Comment by memark** [comment]
@span 
I did get it working on an Ubuntu cluster last year. I remember it was kind of tricky, especially with all the different ports (which are "moderately" documented. :) )

Here are the main parts of the command line I used to start EventStore
`--ext-ip=0.0.0.0 --int-ip=0.0.0.0 --int-http-prefixes=http://*:2112/ --ext-http-prefixes=http://*:2113/ --int-http-port=2112 --ext-http-port=2113 --int-tcp-port=1112 --ext-tcp-port=1113 --int-secure-tcp-port=1114 --ext-secure-tcp-port=1115 --certificate-file=certificate.pfx --certificate-password=some-long-password --use-internal-ssl=false`

As you can see I used a pfx-style file. Turning off "internal ssl" was also a key point for me.

**Comment by ChrisChinchilla** [comment]
This is now done, though I will further overhaul the docs.
