### ISSUE TITLE
DDD CQRS Video Linked on Event Sourcing Basics is not viewable

### ISSUE THREAD

**Issue by tooky** [EventStore/docs.geteventstore.com#151]
This video (http://www.viddler.com/v/dc528842) linked at http://docs.geteventstore.com/introduction/event-sourcing-basics/ is not viewable because viddler reports it as private.

**Comment by pgermishuys** [comment]
I am sure it was the following video.
https://www.youtube.com/watch?v=whCk1Q87_ZI

Can anyone confirm, if so we can point to the youtube one instead.

**Comment by uxp** [comment]
@pgermishuys it's the same video
