### ISSUE TITLE
Unable to access eventstore from another system - they both in same network.

### ISSUE THREAD

**Issue by madhubaabu** [EventStore/docs.geteventstore.com#166]
Hi, 
I have unzip windows version of eventstore and made it run locally. It is working fine when I try to access http://localhost:2113, but when I try to access from another system by given 

http://systemname:2113 or http://ipaddress:2113. No page returned. 

please help me out.
Thanks in advance.

**Comment by gregoryyoung** [comment]
This is the wrong place for such issues. Try https://github.com/eventstore/eventstore it also depends what settings you have run with which would help if you included.
