### ISSUE TITLE
Conflicting paragraphs about head link

### ISSUE THREAD

**Issue by drozzy** [EventStore/docs.geteventstore.com#203]
Reading through the docs on [streams](http://docs.geteventstore.com/http-api/3.9.0/reading-streams/) it seems like these two paragraphs are conflicting. The first one, says that head link is _not_ cacheable, while the second says that you should _only_ bookmark head link:

> It is also important to note that all links with the exception of the head link are fully cachable...

> It is also important to note that you should never bookmark links aside from the head of the stream resource...

**Comment by gregoryyoung** [comment]
They are discussing two things. The first is talking about overall cacheability. The second is referring to navigation (it should always be done with prev/next/etc links). Maybe the second one needs better wording to make it more clear something like:

You should never bookmark links aside from the head of the stream resource and should instead use the links provided by the backend as URIs can change in the future.

**Comment by ChrisChinchilla** [comment]
This has been resolved.
