### ISSUE TITLE
Documentation for projection query language

### ISSUE THREAD

**Issue by drozzy** [EventStore/docs.geteventstore.com#211]
Reopening [this](https://github.com/EventStore/EventStore/issues/1103#issuecomment-262894790) in docs now.

There are still no docs for functions like `when` and `link-to`.

Old docs here: https://github.com/EventStore/EventStore/wiki/Projections-when

**Comment by gregoryyoung** [comment]
http://docs.geteventstore.com/projections/4.0.0/user-defined-projections/

**Comment by gregoryyoung** [comment]
its there just not detailed in usage, that is coming.

**Comment by drozzy** [comment]
Oh, I completely missed it. Thanks.
