### ISSUE TITLE
Docs for filterBy

### ISSUE THREAD

**Issue by drozzy** [EventStore/docs.geteventstore.com#216]
There is no doc for filterBy function anywhere:
http://docs.geteventstore.com/projections/4.0.0/user-defined-projections/

In particular, it should at least state:

- it's signature: `filterBy(state) -> state | null`
- the fact that it operates on state and not on events.
- what the return type being `null` means?

**Comment by jiimaho** [comment]
Still no docs anywhere for this?

**Comment by mjgpy3** [comment]
Resolved by #247
