### ISSUE TITLE
/stats/tcp should be /stats/proc/tcp

### ISSUE THREAD

**Issue by shaan1337** [EventStore/docs.geteventstore.com#261]
https://eventstore.org/docs/http-api/swagger/Stats/Get%20TCP%20connection%20stats.html

https://github.com/EventStore/EventStore/issues/1590

**Comment by ChrisChinchilla** [comment]
Thanks @shaan1337 huh, that's confusing, the codebase shows:

```
service.RegisterAction(new ControllerAction("/stats/tcp", HttpMethod.Get, Codec.NoCodecs, SupportedCodecs), OnGetTcpConnectionStats);
```

Could you maybe explain where the `proc` comes from? Just so I understand :)

**Comment by shaan1337** [comment]
@ChrisChinchilla sorry for the late reply

Thanks, after checking through the code, you're right - these are two different endpoints giving different information and both of them work.

**`/stats/tcp`**
This gives information about active TCP connections. I just tested this by connecting a persistent subscription to an EventStore node:
```
[
  {
    "remoteEndPoint": "127.0.0.1:56791",
    "localEndPoint": "127.0.0.1:1113",
    "clientConnectionName": "ES-a1fe9dfa-b1b1-4daf-8cd1-f1e237383be7",
    "connectionId": "0d521d5e-ddc3-47ab-9b17-e2819c11281b",
    "totalBytesSent": 1037190,
    "totalBytesReceived": 2145208,
    "pendingSendBytes": 0,
    "pendingReceivedBytes": 0,
    "isExternalConnection": true,
    "isSslConnection": false
  }
]%   
```

So maybe we can just change this line to clarify it a bit, what do you think?
`Returns all TCP connection stats for Event Store.`
to
`Returns all active TCP connection stats for Event Store.`

**`/stats/proc/tcp`**
`stats/proc/tcp` comes from the fact that `tcp` subtree is under `proc`
The stats API follows a tree structure, so you can query any subtree.
This is already covered in the docs here:
https://eventstore.org/docs/http-api/swagger/Stats/Get%20specified%20stat.html

**Comment by ChrisChinchilla** [comment]
Thanks @shaan1337 updated and will be deployed soon.
