### ISSUE TITLE
recursive toc loading

### ISSUE THREAD

**Issue by ChrisChinchilla** [EventStore/docs.geteventstore.com#267]
Ref here- https://github.com/EventStore/eventstore.org/issues/29

**Comment by ChrisChinchilla** [comment]
Resolved, thanks for reporting @timbus the JavaScript structure of DocFX is a little brittle…

**Comment by ibruynin** [comment]
@ChrisChinchilla - do you mind sharing how this was resolved? 
I'm seeing the same issue in my docfx project

**Comment by ChrisChinchilla** [comment]
@ibruynin Hmm, I can't exactly remember, but you can see commits to our theme here - https://github.com/EventStore/es-docs-template/commits/master

There's a commit when I fixed it, but I can't quite tell exactly how I did it now. Maybe just looking at our theme will help.

**Comment by ChrisChinchilla** [comment]
@ibruynin That sounds vaguely familiar 🤔

**Comment by dhvik** [comment]
the configuration setting _disableNavbar: false results in the same behavior
