### ISSUE TITLE
No HTTP API docs for group management 

### ISSUE THREAD

**Issue by Xorima** [EventStore/docs.geteventstore.com#268]
Similar issue to #238 
Could we get some documentation on groups with the http api?

**Comment by ChrisChinchilla** [comment]
@Xorima This is now in the HTTP spec docs, but do you mean you would like more tutorial style docs?

**Comment by ChrisChinchilla** [comment]
@Xorima I have just realised that while the definition exists in the Swagger spec that generates the HTTP spec docs you can find on the docs site, it's not actually mentioned in any endpoints, will update asap. Would you also like tutorial style content or would that be enough?

**Comment by Xorima** [comment]
Just the endpoints should do, I am planning some new integrations and this is a key part 😄

**Comment by ChrisChinchilla** [comment]
@Xorima Unless I'm missing something (and I can't find it in the codebase), is this what you were looking for?

https://eventstore.org/docs/http-api/swagger/Users.html

Missing a few details maybe, but hopefully enough for now.
