### ISSUE TITLE
Missing docs on Projections

### ISSUE THREAD

**Issue by haf** [EventStore/docs.geteventstore.com#38]
Fully missing documentation on it. Blog posts don't count.
- [ ] ProjectionManager - and pattern for creating/updating/deleting and rebuilding projections per-svc/ap;p.
- [ ] JS projection function signatures
- [ ] special cases for filtering; [`$all`, `$any` ...?]
- [ ] How to name events to make sense when you have multiple projections
- [ ] [Linearizability and Serializability](http://www.bailis.org/blog/linearizability-versus-serializability/) properties of read models?
- [ ] How stale can they get after a given write? What about in the distributed/consistent cluster mode?

**Comment by gregoryyoung** [comment]
Projections are not released software they are in beta and subject to change.

**Comment by haf** [comment]
None the less, you have a few which seem vital in all of your documentation, namely 'per type' and 'per category' and 'per stream' projections.

Also, if they indeed are in beta, you'd be wise to start a discussion about some of these things and solicit community feedback. E.g. what consistency semantics will you have? Or is the naming apt?

**Comment by gregoryyoung** [comment]
"you have a few which seem vital in all of your documentation, namely 'per
type' and 'per category' and 'per stream' projections."

link?

"Also, if they indeed are in beta, you'd be wise to start a discussion
about some of these things and solicit community feedback. E.g. what
consistency semantics will you have?"

projections are run asynchronously not with the writing of an event.

On Mon, Jan 19, 2015 at 11:37 PM, Henrik Feldt <notifications@github.com>
wrote:

> None the less, you have a few which seem vital in all of your
> documentation, namely 'per type' and 'per category' and 'per stream'
> projections.
>
> Also, if they indeed are in beta, you'd be wise to start a discussion
> about some of these things and solicit community feedback. E.g. what
> consistency semantics will you have? Or is the naming apt?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/docs.geteventstore.com/issues/38#issuecomment-70565490>
> .
>



-- 
Studying for the Turing test

**Comment by haf** [comment]
Node A, Projection a.

Client A reads a, gets value(a).

Is value(a) visible on Node B for Client A, always? For example.

**Comment by gregoryyoung** [comment]
Like any other data the output of projections is linearized. Any node that
is not a master may or may not have any piece of data (quorum). There is
nothing special about projections in this regard.

On Tuesday, January 20, 2015, Henrik Feldt <notifications@github.com> wrote:

> Node A, Projection a.
>
> Client A reads a, gets value(a).
>
> Is value(a) visible on Node B for Client A, always? For example.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/docs.geteventstore.com/issues/38#issuecomment-70609659>
> .
>


-- 
Studying for the Turing test

**Comment by haf** [comment]
Right, so which node is master - what algorithm is being used to select master? What if the master changes; does it not respond to requests until it's up to date with the last master's visible data (similar to how Raft may have master-committed WAL-entries, that are reverted on master change, if there's no consensus for them)? Does this mean a read to a master can sometimes never be repeated?

**Comment by gregoryyoung** [comment]
A record is not visible until acks have been received from a quorum of
nodes. As such you can never get a read from master that will disappear in
a deposed master scenario.

On Tue, Jan 20, 2015 at 10:12 AM, Henrik Feldt <notifications@github.com>
wrote:

> Right, so which node is master - what algorithm is being used to select
> master? What if the master changes; does it not respond to requests until
> it's up to date with the last master's visible data (similar to how Raft
> may have master-committed WAL-entries, that are reverted on master change,
> if there's no consensus for them)? Does this mean a read to a master can
> sometimes never be repeated?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/docs.geteventstore.com/issues/38#issuecomment-70618413>
> .
>



-- 
Studying for the Turing test

**Comment by gregoryyoung** [comment]
Its actually discussed briefly here
http://geteventstore.com/blog/20130301/ensuring-writes-multi-node-replication/

On Tue, Jan 20, 2015 at 3:34 PM, Greg Young <gregoryyoung1@gmail.com> wrote:

> A record is not visible until acks have been received from a quorum of
> nodes. As such you can never get a read from master that will disappear in
> a deposed master scenario.
>
> On Tue, Jan 20, 2015 at 10:12 AM, Henrik Feldt <notifications@github.com>
> wrote:
>
>> Right, so which node is master - what algorithm is being used to select
>> master? What if the master changes; does it not respond to requests until
>> it's up to date with the last master's visible data (similar to how Raft
>> may have master-committed WAL-entries, that are reverted on master change,
>> if there's no consensus for them)? Does this mean a read to a master can
>> sometimes never be repeated?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/EventStore/docs.geteventstore.com/issues/38#issuecomment-70618413>
>> .
>>
>
>
>
> --
> Studying for the Turing test
>



-- 
Studying for the Turing test

**Comment by ChrisChinchilla** [comment]
Mostly covered now, but I am going to note some of the top checklist to check for gaps in the future.
