### ISSUE TITLE
Docs from plain csc-xml file?

### ISSUE THREAD

**Issue by haf** [EventStore/docs.geteventstore.com#39]
This is all you need to do:

```
#!/usr/bin/env sh
mono tools/NuGet.exe -ExcludeVersion -OutputDirectory packages EventStore.Client
cd packages/EventStore.Client/lib/net40/
mdoc update -i EventStore.ClientAPI.xml -o en EventStore.ClientAPI.dll
mdoc export-html -o docs en
cd docs
serve  # from 'gem install serve'
open http://localhost:4000
```

And then push the generated html to get quick API docs from what you have already written.

Looks like this:
![screen shot 2014-12-07 at 22 42 16](https://cloud.githubusercontent.com/assets/193115/5332767/5a20ac94-7e62-11e4-9d5d-6cbf3681469e.png)

![screen shot 2014-12-07 at 22 42 59](https://cloud.githubusercontent.com/assets/193115/5332769/6d9160c0-7e62-11e4-8a6c-622654d8c7c3.png)

**Comment by ChrisChinchilla** [comment]
@haf @rcknight This is now covered using DocFX, which is similar to sandcastle.
