### ISSUE TITLE
Deploy with Puppet

### ISSUE THREAD

**Issue by jbradford** [EventStore/docs.geteventstore.com#89]
Currently we have a page in the Server docs (3.0.0-3.0.2-pre) for deploying with puppet, however the first note on that page states it only applies to Event Store 2.0.0. I suggest this either needs to be updated, or somehow moved out of the Event Store 3 docs.

**Comment by gregoryyoung** [comment]
I'd give it a try my guess is it still works.

On Thursday, January 22, 2015, Jon Bradford <notifications@github.com>
wrote:

> Currently we have a page in the Server docs (3.0.0-3.0.2-pre) for
> deploying with puppet, however the first note on that page states it only
> applies to Event Store 2.0.0. I suggest this either needs to be updated, or
> somehow moved out of the Event Store 3 docs.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/docs.geteventstore.com/issues/89>.
>


-- 
Studying for the Turing test

**Comment by jbradford** [comment]
Seems to be very specific to v2 in the script, checked with @rcknight and doesn't seem to be usable any more, going to move to wiki-orphans for now so the content is not lost.
