### ISSUE TITLE
Server Pages Requiring Updating

### ISSUE THREAD

**Issue by jbradford** [EventStore/docs.geteventstore.com#90]
- [x] - Access Control Lists
- [x] - Setting up a Cluster with Manager Nodes
- [x] - Command Line Arguments #87 (https://github.com/EventStore/EventStore/issues/381)
- [x] - Deploy with Puppet #89 
- [x] - Architecture Setup
- [x] - Setting up SSL in Linux
- [x] - Setting up SSL in Windows
- [x] - Setting up Varnish in Linux

**Comment by gregoryyoung** [comment]
What's the issue with acls?

On Thursday, January 22, 2015, Jon Bradford <notifications@github.com>
wrote:

> [ ] - Access Control Lists
> [ ] - Setting up a Cluster with Manager Nodes
> [ ] - Command Line Arguments #87
> <https://github.com/EventStore/docs.geteventstore.com/issues/87> (
> EventStore/EventStore#381
> <https://github.com/EventStore/EventStore/issues/381>)
> [ ] - Deploy with Puppet #89
> <https://github.com/EventStore/docs.geteventstore.com/issues/89>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/docs.geteventstore.com/issues/90>.
>


-- 
Studying for the Turing test

**Comment by jbradford** [comment]
Should have been more specific in first post, these are the pages that haven't been reformated since the docs move.  I believe the content of them is fine.

**Comment by gregoryyoung** [comment]
Ah ok!

On Thursday, January 22, 2015, Jon Bradford <notifications@github.com>
wrote:

> Should have been more specific in first post, these are the pages that
> haven't been reformated since the docs move. I believe the content of them
> is fine.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/docs.geteventstore.com/issues/90#issuecomment-71012861>
> .
>


-- 
Studying for the Turing test

**Comment by jbradford** [comment]
Added the transferred pages (see #92) to the list in the original post.
