### ISSUE TITLE
HTTP API Misfiled Pages

### ISSUE THREAD

**Issue by jbradford** [EventStore/docs.geteventstore.com#92]
- Architecture Setup
- Setting up SSL in Linux/Windows
- Setting up Varnish

Should these pages be in the server docs rather than the HTTP API?

**Comment by gregoryyoung** [comment]
Could be worth moving. I think we could use a better overall "setups" doc

On Thursday, January 22, 2015, Jon Bradford <notifications@github.com>
wrote:

> Does this page belong in the HTTP API section? It seems to deal more with
> deployment concerns than the HTTP API itself.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/docs.geteventstore.com/issues/92>.
>


-- 
Studying for the Turing test

**Comment by jbradford** [comment]
I would agree, for now I'll move them into the server docs but I suspect sometime in the near future we should review all setup based docs.
