### ISSUE TITLE
The video link at dddcqrs.com does not exist

### ISSUE THREAD

**Issue by AnthonyMastrean** [EventStore/docs.geteventstore.com#98]
On the [Event Sourcing Basics][1] page, the link at the bottom for "CQRS Video" goes to 

```
http://dddcqrs.com/
```

which is parked or taken over by ads. I don't know what video was intended here. If we can find it, let's link it. Or take this link down, as it poorly represents geteventstore.

 [1]: https://github.com/EventStore/docs.geteventstore.com/blob/gh-pages/introduction/event-sourcing-basics.md

**Comment by danleech** [comment]
Thanks for letting us know!

**Comment by jbradford** [comment]
Does anyone know which video this is and if it still exists so we can still link to it?

**Comment by gregoryyoung** [comment]
Its my 6 hour vid its on the dddcqrs website i forget the name bur google
should bring it up

**Comment by pgermishuys** [comment]
This one? http://www.viddler.com/v/dc528842

**Comment by gregoryyoung** [comment]
yes

On Wed, Jan 28, 2015 at 8:07 AM, Pieter Germishuys <notifications@github.com
> wrote:

> This one? http://www.viddler.com/v/dc528842
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/docs.geteventstore.com/issues/98#issuecomment-71785978>
> .
>



-- 
Studying for the Turing test

**Comment by jkuchar** [comment]
Link is broken again. Account is private. Any ideas how to get there?

**Comment by jkuchar** [comment]
Found it on youtube: https://www.youtube.com/watch?v=whCk1Q87_ZI
